export const teamsDetails = [
    {
        Nm: 'Tottenham Hotspur',
        ID: '3339',
        tbd: 0,
        Img: 'enet/8586.png',
        Abr: 'TOT',
        firstColor: '132257',
        secondColor: 'ffffff',
        Pids: {
          '12': [ 'SBTP_1_242' ],
          '15': [ '18' ],
          '112': [ 'SBTP_2_1000000083' ]
        },
        CoNm: 'England',
        CoId: 'ENG',
        HasVideo: true,
        NewsTag: '/team/tottenham-2021020913320920836-89/',
        national: false,
        HasSquad: true,
        TO: 7,
        Stages: [
          {
            Events: [Array],
            Sid: '18173',
            Snm: 'Premier League',
            Sds: 'Premier League',
            Scd: 'premier-league',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '65',
            CompN: 'Premier League',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-premier-league.png',
            firstColor: '3F1152',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '237',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '18298',
            Snm: 'EFL Cup: Round 3',
            Scd: 'efl-cup-round-3',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '76',
            CompN: 'EFL Cup',
            CompST: '',
            CompD: 'England',
            badgeUrl: '2023-england-efl-cup.png',
            firstColor: 'B90B2F',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '345',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '14414',
            Snm: 'Premier League 23/24',
            Sds: 'Premier League 23/24',
            Scd: 'premier-league-2023-2024',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '617',
            CompN: 'Premier League 23/24',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-premier-league.png',
            firstColor: '3F1152',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '237',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '15949',
            Snm: 'FA Cup: Round 4',
            Scd: 'fa-cup-round-4',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '694',
            CompN: 'FA Cup 23/24',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-england-fa-cup.png',
            firstColor: '03264C',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '415',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '15948',
            Snm: 'FA Cup: Round 3',
            Scd: 'fa-cup-round-3',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '694',
            CompN: 'FA Cup 23/24',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-england-fa-cup.png',
            firstColor: '03264C',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '415',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '14553',
            Snm: 'EFL Cup: Round 2 23/24',
            Scd: 'efl-cup-round-2-2023-2024',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '652',
            CompN: 'EFL Cup 23/24',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-england-efl-cup.png',
            firstColor: 'B90B2F',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '345',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '18545',
            Snm: 'Featured Club Friendlies',
            Scd: 'featured-club-friendlies',
            Cid: '555',
            Cnm: 'Club Friendlies',
            CnmT: 'club-friendlies',
            Csnm: 'Club Friendlies',
            Ccd: 'club-friendlies',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '267',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '16386',
            Snm: 'Club Friendlies 2024',
            Sds: 'Club Friendlies 2024',
            Scd: 'club-friendlies-2024',
            Cid: '555',
            Cnm: 'Club Friendlies',
            CnmT: 'club-friendlies',
            Csnm: 'Club Friendlies',
            Ccd: 'club-friendlies',
            CompId: '310',
            CompN: 'Club Friendlies',
            CompD: '2024',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '267',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '10765',
            Snm: 'Premier League 22/23',
            Sds: 'Premier League 22/23',
            Scd: 'premier-league-2022-2023',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '342',
            CompN: 'Premier League 22/23',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-premier-league.png',
            firstColor: '3F1152',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '237',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '12369',
            Snm: 'Round of 16 22/23',
            Scd: 'round-of-16-2022-2023',
            Cid: '564',
            Cnm: 'Champions League 22/23',
            CnmT: 'champions-league-2223',
            Ccd: 'champions-league-2022-2023',
            CompId: '380',
            CompN: 'Champions League 22/23',
            CompD: 'UEFA',
            badgeUrl: '2023-champions-league.png',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '1445',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '11680',
            Snm: 'Group D 22/23',
            Scd: 'group-d-2022-2023',
            Cid: '564',
            Cnm: 'Champions League 22/23',
            CnmT: 'champions-league-2223',
            Ccd: 'champions-league-2022-2023',
            CompId: '380',
            CompN: 'Champions League 22/23',
            CompD: 'UEFA',
            badgeUrl: '2023-champions-league.png',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '1445',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '10881',
            Snm: 'EFL Cup 22/23',
            Sds: 'EFL Cup 22/23',
            Scd: 'efl-cup-2022-2023',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '389',
            CompN: 'EFL Cup 22/23',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-england-efl-cup.png',
            firstColor: 'B90B2F',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '345',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '7126',
            Snm: 'Premier League 21/22',
            Sds: 'Premier League 21/22',
            Scd: 'premier-league-2021-2022',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '10',
            CompN: 'Premier League 21/22',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-premier-league.png',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '237',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '8012',
            Snm: 'Group G 21/22',
            Scd: 'group-g-2021-2022',
            Cid: '513',
            Cnm: 'Europa Conference League 21/22',
            CnmT: 'europa-conference-league-2122',
            Csnm: 'Europa Conference League 21/22',
            Ccd: 'europa-conference-league-2021-2022',
            CompId: '30',
            CompN: 'Europa Conference League 21/22',
            CompD: 'UEFA',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '1315',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '7118',
            Snm: 'Qualification 21/22',
            Scd: 'qualification',
            Cid: '513',
            Cnm: 'Europa Conference League 21/22',
            CnmT: 'europa-conference-league-2122',
            Csnm: 'Europa Conference League 21/22',
            Ccd: 'europa-conference-league-2021-2022',
            CompId: '30',
            CompN: 'Europa Conference League 21/22',
            CompD: 'UEFA',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '1315',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '8465',
            Snm: 'FA Cup 21/22',
            Sds: 'FA Cup',
            Scd: 'fa-cup-2021-2022',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '50',
            CompN: 'FA Cup 21/22',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-england-fa-cup.png',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '415',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '7233',
            Snm: 'EFL Cup 21/22',
            Sds: 'EFL Cup 21/22',
            Scd: 'efl-cup-2021-2022',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '33',
            CompN: 'EFL Cup 21/22',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-england-efl-cup.png',
            firstColor: 'B90B2F',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '345',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '292',
            Snm: 'Premier League 20/21',
            Sds: 'Premier League 20/21',
            Scd: 'premier-league-2020-2021',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '9',
            CompN: 'Premier League 20/21',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-premier-league.png',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '237',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '2067',
            Snm: 'Round of 16 20/21',
            Sds: 'Round of 16 20/21',
            Scd: 'round-of-16-2019-2020',
            Cid: '542',
            Cnm: 'Europa League 20/21',
            CnmT: 'europa-league-2021',
            Ccd: 'europa-league-20-21',
            CompId: '132',
            CompN: 'Europa League 20/21',
            CompD: 'UEFA',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '332',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '5446',
            Snm: 'Round of 32 20/21',
            Sds: 'Round of 32 20/21',
            Scd: 'round-of-32-2020-2021',
            Cid: '542',
            Cnm: 'Europa League 20/21',
            CnmT: 'europa-league-2021',
            Ccd: 'europa-league-20-21',
            CompId: '132',
            CompN: 'Europa League 20/21',
            CompD: 'UEFA',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '332',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '5020',
            Snm: 'Group J 20/21',
            Sds: 'Group J 20/21',
            Scd: 'group-j',
            Cid: '542',
            Cnm: 'Europa League 20/21',
            CnmT: 'europa-league-2021',
            Ccd: 'europa-league-20-21',
            CompId: '132',
            CompN: 'Europa League 20/21',
            CompD: 'UEFA',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '332',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '5010',
            Snm: 'Qualification 20/21',
            Sds: 'Qualification 20/21',
            Scd: 'qualification-2020-2021',
            Cid: '542',
            Cnm: 'Europa League 20/21',
            CnmT: 'europa-league-2021',
            Ccd: 'europa-league-20-21',
            CompId: '132',
            CompN: 'Europa League 20/21',
            CompD: 'UEFA',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '332',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '5197',
            Snm: 'FA Cup 20/21',
            Sds: 'FA Cup 20/21',
            Scd: 'fa-cup-2020-2021',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            badgeUrl: '2023-england-fa-cup.png',
            firstColor: 'B90B2F',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '415',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '6081',
            Snm: 'Premier League 19/20',
            Sds: 'Premier League 19/20',
            Scd: 'premier-league-2019-2020',
            Cid: '34',
            Cnm: 'England',
            CnmT: 'england',
            Csnm: 'England',
            Ccd: 'england',
            CompId: '549',
            CompN: 'Premier League 19/20',
            CompST: 'England',
            CompD: 'England',
            badgeUrl: '2023-premier-league.png',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '237',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '13063',
            Snm: 'Round of 16 19/20',
            Scd: 'round-of-16-2019-2020',
            Cid: '544',
            Cnm: 'Champions League 19/20',
            CnmT: 'champions-league-1920',
            Ccd: 'champions-league-19-20',
            CompId: '143',
            CompN: 'Champions League 19/20',
            CompD: 'UEFA',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '1505',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '13053',
            Snm: 'Group B 19/20',
            Scd: 'group-b-2019-2020',
            Cid: '544',
            Cnm: 'Champions League 19/20',
            CnmT: 'champions-league-1920',
            Ccd: 'champions-league-19-20',
            CompId: '143',
            CompN: 'Champions League 19/20',
            CompD: 'UEFA',
            Scu: 0,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '1505',
            Sids: {}
          },
          {
            Events: [Array],
            Sid: '13788',
            Snm: 'Club Friendlies 2023',
            Sds: 'Club Friendlies 2023',
            Scd: 'club-friendlies',
            Cid: '555',
            Cnm: 'Club Friendlies',
            CnmT: 'club-friendlies',
            Csnm: 'Club Friendlies',
            Ccd: 'club-friendlies',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '267',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '9061',
            Snm: 'Club Friendlies 2022',
            Scd: 'club-friendlies-2022',
            Cid: '555',
            Cnm: 'Club Friendlies',
            CnmT: 'club-friendlies',
            Csnm: 'Club Friendlies',
            Ccd: 'club-friendlies',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '267',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '5614',
            Snm: 'Club Friendlies 2021',
            Scd: 'club-friendlies-2021',
            Cid: '555',
            Cnm: 'Club Friendlies',
            CnmT: 'club-friendlies',
            Csnm: 'Club Friendlies',
            Ccd: 'club-friendlies',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '267',
            Sids: [Object]
          },
          {
            Events: [Array],
            Sid: '1187',
            Snm: 'Club Friendlies 2020',
            Scd: 'club-friendlies-2020',
            Cid: '555',
            Cnm: 'Club Friendlies',
            CnmT: 'club-friendlies',
            Csnm: 'Club Friendlies',
            Ccd: 'club-friendlies',
            Scu: 1,
            Chi: 0,
            Shi: 0,
            Spid: 1,
            Tid: '267',
            Sids: {}
          }
        ],
        StatS: [
          '18173', '14414',
          '14553', '10765',
          '12369', '11680',
          '10881', '7126',
          '7233',  '292',
          '5020',  '5010'
        ],
        StatTeamS: [
          '18173', '14414',
          '14553', '10765',
          '12369', '11680',
          '10881', '7126',
          '292',   '5020',
          '5010'
        ],
        StatPlayerS: [
          '18173', '14414',
          '14553', '10765',
          '12369', '11680',
          '10881', '7126',
          '7233',  '292',
          '5020',  '5010'
        ]
      }
]